# This workflow tests Ocean on Linux (static)
# Based on : https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: Test Ocean on Linux (static)

on:
  workflow_run:
    workflows: ["Build Ocean on Linux (static)"]
    branches: [main]
    types:
      - completed

jobs:
  test:
    uses: ./.github/workflows/test_ocean_linux_helper.yml
    secrets: inherit
